package controller.responses;

public enum LoginMenuResponses {
    USER_CREATE_SUCCESSFUL,
    USER_USERNAME_ALREADY_EXISTS,
    PASS_NOT_SAME,
    USER_EMAIL_ALREADY_EXISTS,
    EMAIL_IS_INVALID,
    IS_NOT_USER,
    WELCOM,
    USER_LOGIN_SUCCESSFUL,
    USER_USERNAME_PASSWORD_NOT_MATCHED,
    USER_LOGOUT_SUCCESSFUL,
    USER_REMOVE_SUCCESSFUL;
}
