package controller.responses;

public enum ProfileMenuResponses {
    USER_ALREADY_TAKEN,
    INCLOUD_ATLEAST_CHAR,
    COUNTAINS_SPECIAL_CHAR,
    SAME_USENAME,
    PASSWORD_CHANGE_SUCCESSFUL,
    USERNAME_CHANGE_SUCCESSFUL,
    PASS_NOT_STRONG,
    CURRENT_PASSWORD_INVALID,
    IDENTICAL_PASSWORDS
}
